# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLrltPkwCi-ShlIQTaGPcw9SozqVxki3
"""

import requests
from bs4 import BeautifulSoup

# URL of the website to scrape
url = "https://techcrunch.com/2024/04/30/sams-clubs-ai-powered-exit-tech-reaches-20-of-stores/"

# Send a GET request to the URL
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the page
    soup = BeautifulSoup(response.content, "html.parser")

    # Find the main content of the article
    article_content = soup.find("div", class_="article-content")

    # Extract the text content of the article
    article_text = article_content.get_text(separator="\n")

    # Print the extracted article content
    print(article_text)
else:
    print("Failed to fetch the webpage. Status code:", response.status_code)